### ISSUE TITLE
[SUGG] Use `MEMORY USAGE`

### ISSUE THREAD

**Issue by itamarhaber** [winjeg/rma4go#1]
Hello dear author,

This is a nice utility, similar to what is done by `redis-cli --bigkeys` but more detailed. 

As an optimization, you would do much better in terms of accuracy and performance if you replace the size/length calculations with a call to [`MEMORY USAGE`](https://redis.io/commands/memory-usage) to obtain the memory footprint of a given key.

**Comment by winjeg** [comment]
since it's a new feature since redis 4.0.0
I think I will do it this way.

1. check the redis version , via command `info`
2. if version >= 4.0 use the command you mentioned
3. else use the original method

thanks for the advice

by the way,  if you're interested, you can submit a pull request.

**Comment by winjeg** [comment]
it should be resolved by now.
