### ISSUE TITLE
支持redis集群？

### ISSUE THREAD

**Issue by jeremyxu2010** [winjeg/rma4go#2]
我看了`client/client.go:20`处的代码，好像目前只是查询单机redis的，可否支持下redis集群？
我看底层已经有相应的接口了`github.com/winjeg/redis/universal.go:172`了

**Comment by winjeg** [comment]
这个集群的，其实在我实际使用过程中呢， 它scan的结果其实是跟单机的有些区别的， 有些可能scan的不是很准确，应该是redis 驱动的一些问题， 这个驱动还有一些其他小问题，得再看看。
另外， 集群的话，  对于每个节点的话可以都运行这个命令，理论上讲这样scan的结果是不会有错的。

**Comment by jeremyxu2010** [comment]
@winjeg 嗯，目前我就是查询每个节点的，但还是希望能直接统计整个集群，这样更全局一点

**Comment by winjeg** [comment]
我尝试在 v0.0.9 中加入了这个特性， 你可以尝试一下， 不影响原来的使用，多了一条命令

```
rma4go -c "localhost:123,localhost:456,localhost:21312"
```

这个issue 我先关了， 有什么问题，你可以再打开
