### ISSUE TITLE
建议用travis-ci做一下自动构建

### ISSUE THREAD

**Issue by jeremyxu2010** [winjeg/rma4go#3]
建议参考[https://docs.travis-ci.com/user/deployment/releases/](https://docs.travis-ci.com/user/deployment/releases/)做一下自动构建，这样用户可以直接在release里下载到各平台的二进制程序

**Comment by winjeg** [comment]
可以的， 你有空嘛， 可以代劳一下么😀

**Comment by jeremyxu2010** [comment]
@winjeg ok，我抽空处理一下，做好了给你发PR

**Comment by winjeg** [comment]
OK, 赞
