### ISSUE TITLE
程序非常吃内存

### ISSUE THREAD

**Issue by funcc** [winjeg/rma4go#5]
程序非常吃内存，内存小点的直接被OOM-kill了。
看作者文档，说是分段扫描、压缩的。但看代码stat.Compact() 在for 循环之外，疑似读取所有keys再压缩的

另外，几个GB的redis，就需要很久时间，能不能考虑使用pipeline方式使用redis.

最后提个小需求，能不能添加个scan的参数，默认是*，有时候知道key前缀，想快速知道结果。

**Comment by winjeg** [comment]
pipeline  方式的话，其实不一定可以， 不过可以考虑增加一个参数，制定目标是集群还是单机， 单机可以用pipeline, 集群就不行。 
另外几个问题有可能存在， 如果你感兴趣的话， 有没有兴趣搞一下？
1. 添加支持 match pattern的功能
2. 添加支持 区分集群与单机的功能
3. 在单机下可以选用pipeline 优化查询速度

我可能不一定啥时候有空...

**Comment by dcongee** [comment]
5G数据，2200W KEY，消耗系统内存70多G，都没能分析出结果。

**Comment by winjeg** [comment]
> 5G数据，2200W KEY，消耗系统内存70多G，都没能分析出结果。

https://github.com/winjeg/rma4go/releases/tag/v0.1.0
我修改了一下， 看看这个是否能解决你的问题

**Comment by winjeg** [comment]
如果没啥问题我先close 了， 有问题可以继续reopen 反馈

**Comment by dcongee** [comment]
> > 5G数据，2200W KEY，消耗系统内存70多G，都没能分析出结果。
> 
> https://github.com/winjeg/rma4go/releases/tag/v0.1.0
> 我修改了一下， 看看这个是否能解决你的问题

有时间再试试；谢谢了。
