### ISSUE TITLE
The cluster mode could not be used

### ISSUE THREAD

**Issue by wjf870128** [winjeg/rma4go#6]
redis release:5.0.8
cmd:./rma4go -c "127.0.0.1:6380,127.0.0.1:6379,127.0.0.1:6384,127.0.0.1:6385" -a xxxxx
but there is no result
else:
./rma4go -r 127.0.0.1 -a xxxxxx -p 6380 -m "b*"
the result is:

all keys statistics

| PATTERN | KEY NUM | KEY SIZE | DATA SIZE | EXPIRE IN HOUR | EXPIRE IN DAY | EXPIRE IN WEEK | EXPIRE OUT WEEK | NEVER EXPIRE |
|---------|---------|----------|-----------|----------------|---------------|----------------|-----------------|--------------|
| b*      |       1 |        1 |        48 |              0 |             0 |              0 |               0 |            1 |
| total   |       1 |        1 |        48 |              0 |             0 |              0 |               0 |            1 |

string keys statistics

| PATTERN | KEY NUM | KEY SIZE | DATA SIZE | EXPIRE IN HOUR | EXPIRE IN DAY | EXPIRE IN WEEK | EXPIRE OUT WEEK | NEVER EXPIRE |
|---------|---------|----------|-----------|----------------|---------------|----------------|-----------------|--------------|
| b*      |       1 |        1 |        48 |              0 |             0 |              0 |               0 |            1 |
| total   |       1 |        1 |        48 |              0 |             0 |              0 |               0 |            1 |

**Comment by winjeg** [comment]
I don't have time currently.  I may attend to this issue later.

**Comment by winjeg** [comment]
> redis release:5.0.8
> cmd:./rma4go -c "127.0.0.1:6380,127.0.0.1:6379,127.0.0.1:6384,127.0.0.1:6385" -a xxxxx
> but there is no result
> else:
> ./rma4go -r 127.0.0.1 -a xxxxxx -p 6380 -m "b*"
> the result is:
> 
> all keys statistics
> 
> PATTERN	KEY NUM	KEY SIZE	DATA SIZE	EXPIRE IN HOUR	EXPIRE IN DAY	EXPIRE IN WEEK	EXPIRE OUT WEEK	NEVER EXPIRE
> b*	1	1	48	0	0	0	0	1
> total	1	1	48	0	0	0	0	1
> string keys statistics
> 
> PATTERN	KEY NUM	KEY SIZE	DATA SIZE	EXPIRE IN HOUR	EXPIRE IN DAY	EXPIRE IN WEEK	EXPIRE OUT WEEK	NEVER EXPIRE
> b*	1	1	48	0	0	0	0	1
> total	1	1	48	0	0	0	0	1

I don't have time currently. I may attend to this issue later.

Please paste your key cluster configuration here.

**Comment by winjeg** [comment]
It turned out the driver doesn't really support cluster scans.
So intead of giving all key statistics in summary i listed analysis result for each node instead.
This is the easiest way to solve the problem for now.
If you want the summary of all results. You can do it mannualy via a tool like "excel"
